# C/C++ with GCC
# Build your C/C++ project with GCC using make.
# Add steps that publish test results, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/c-cpp/gcc

trigger:
  - master

jobs:
- job: Ubuntu

  pool:
    vmImage: 'ubuntu-latest'

  steps:
  - script: |
      sudo apt-get update -qq
      sudo apt-get install -y --force-yes libsdl2-dev libsdl2-ttf-dev libasound2-dev libxinerama-dev libxi-dev qt5-default
    displayName: 'dependencies'
  - script: |
      make -j4 SUBTARGET=tiny IGNORE_GIT=1
    displayName: 'make'

- job: Windows

  pool:
    vmImage: 'windows-latest'

  steps:
  - script: |
      set MINGW32=%PATH%
      make -j4 SUBTARGET=tiny IGNORE_GIT=1
    displayName: 'make MinGW'